org: kasuboski
app: hello-python-serverless
service: hello-python-serverless

provider:
  name: aws
  runtime: python3.8

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: get
